syllabus:
  description: Guidance for Node architecture and tooling choices.
  topics:
    - TypeScript vs JavaScript
    - Design practicies
      - Options object for optional parameters
      - Hexagonal architecture
  